export const SOCKET_EVENTS = {
  JOIN_CHANNEL: 'join_channel',
  LEAVE_CHANNEL: 'leave_channel',
  SEND_MESSAGE: 'send_message',
  SEND_ALERT: 'send_alert',
  TYPING_START: 'typing_start',
  TYPING_STOP: 'typing_stop',
  NEW_MESSAGE: 'new_message',
  NEW_ALERT: 'new_alert',
  USER_TYPING: 'user_typing',
  LIVE_SESSION_STARTED: 'live_session_started',
  TIER_UPGRADED: 'tier_upgraded',
  MESSAGE_DELETED: 'message_deleted',
  MESSAGE_UPDATED: 'message_updated',
  REACTION_ADDED: 'reaction_added',
  REACTION_REMOVED: 'reaction_removed',
  DM_NEW_MESSAGE: 'dm_new_message',
  DM_TYPING: 'dm_typing',
} as const;
